#{
  show heading: none
  heading(numbering: none)[Bảng thuật ngữ]
}
#align(center, text(16pt, strong("DANH MỤC TỪ VIẾT TẮT")))

*CF-Font* Content Fusion Font. ……

*CL-SCR* Cross-Lingual Style Contrastive Refinement. ……

*DCN* Deformable Convolutional Networks. ……

*DDPM* Denoising Diffusion Probabilistic Models. ……

*DFS* Deep Feature Similarity. ……

*DG-Font* Deformable Generative Network. ……

*DPM-Solver* Diffusion Probabilistic Model Solver. ……

*FID* Fréchet Inception Distance. ……

*GAN* Generative Adversarial Network. ……

*GT* Ground Truth. ……

*L1* Mean Absolute Error. ……

*LPIPS* Learned Perceptual Image Patch Similarity. ……

*MCA* Multi-scale Content Aggregation. ……

*MSE* Mean Squared Error. ……

*RSI* Reference-Structure Interaction. ……

*SCR* Style Contrastive Refinement. ……

*SFUC* Seen Font, Unseen Character. ……

*SOTA* State-of-the-Art. ……

*SSIM* Structural Similarity Index. ……

*UFSC* Unseen Font, Seen Character. ……